// Minifies src/loader/loader.js into src/loader/loader.min.ts (a string the embed route serves).
// Run by `pnpm build:loader`; the generated file is committed and a test fails if it drifts.
import { readFileSync, writeFileSync } from 'node:fs';
import { transformSync } from 'esbuild';

const src = readFileSync(new URL('../src/loader/loader.js', import.meta.url), 'utf8');
// The loader body uses a top-level `return`, so wrap it in a function for esbuild, then unwrap.
const wrapped = `globalThis.__loader=function(c){${src}\n}`;
const { code } = transformSync(wrapped, { minify: true, target: 'es2017', charset: 'ascii', legalComments: 'none' });
const body = code.trim().replace(/^globalThis\.__loader=/, '').replace(/;$/, '');
const out = `// GENERATED by scripts/build-loader.mjs from loader.js - do not edit.\nexport const LOADER_FUNCTION = ${JSON.stringify(body)};\n`;
writeFileSync(new URL('../src/loader/loader.min.ts', import.meta.url), out);
console.log(`loader: ${body.length} bytes minified`);
